### PR TITLE
Steve/create shared components

### PR DESCRIPTION
**Pull request by StephenBecker**
Adds the item card component and popup component for preparation instructions
Adds a demo route to test the component until apis are set up
Reformats dev instructions

image

### CODE REVIEW

**Comment by ghost** [comment]
I like it.

**Comment by yaelBrown** [comment]
Looks nice, I am checking it now.

**Comment by yaelBrown** [comment]
Do you have this file (or using it)?

'reactjs-popup/dist/index.css' 

it is not compiling. 

edit: disregard, I got it.

**Comment by StephenBecker** [comment]
thanks for catching that, I thought I had removed the need for it, but I did not wipe out my node_modules folder to test...

**Pull request merged**
